version: "3"
services:
  frontend:
    build:
      context: ./client # Client Folder
    ports:
      - "5173:5173"
    depends_on:
      - backend
  backend:
    build:
      context: ./server # Backend Server
    ports:
      - "8000:8000"