version: "3"
services:
  frontend:
    build:
      context: ./client # Client Folder
    environment: 
      VITE_API_URL: "http://localhost:8000"

    ports:
      - "5173:5173"
    depends_on:
      - backend
  backend:
    build:
      context: ./server # Backend Server
    ports:
      - "8000:8000"
    environment:
      MONGODB_URI: "mongodb+srv://user:MX0oV3MHiqM9WIN7@cluster0.1esfo.mongodb.net/?retryWrites=true&w=majority"
      PORT: 8000
      ENVIRONMENT: "dev"  # Replace with your MongoDB URI